# Generated by Django 4.0.4 on 2022-06-01 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarredProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starred', to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starred', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Starred Product',
                'verbose_name_plural': 'Starred Products',
                'unique_together': {('product', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
