# Generated by Django 4.0.4 on 2022-06-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Open'), ('in_progress', 'Being processed'), ('closed', 'Closed')], max_length=50),
        ),
    ]
